version: '3.7'

services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 80:5000
    restart: always
    environment:
      DEBUG: 1
    volumes:
      - ./front:/app
    networks:
      - mern_network
    depends_on:
      - mongodb
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back 
    volumes:
      - ./back/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      # env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - mern_network

  mongodb:
    image: mongo:4.4
    container_name: db
    ports:
      - 27017:27017
    networks:
      - mern_network






networks:
  mern_network:
    driver: bridge

